### ISSUE TITLE
can not compile after update djinni

### ISSUE THREAD

**Issue by secrecysiu** [Piasy/AudioMixer#2]
- (PYAAudioBuffer*)mix {
    audio_mixer::AudioMixer* nativeMixer =
        (audio_mixer::AudioMixer*)[_nativeMixer nativeMixer];
    if (nativeMixer) {
        _buffer.size = nativeMixer->Mix(_buffer.data);
    }

    return _buffer;
}

- (PYAAudioBuffer*)addRecordedDataAndMix:(void*)data size:(int32_t)size {
    audio_mixer::AudioMixer* nativeMixer =
        (audio_mixer::AudioMixer*)[_nativeMixer nativeMixer];
    if (nativeMixer) {
        _buffer.size =
            nativeMixer->AddRecordedDataAndMix(data, size, _buffer.data);
    }

    return _buffer;
}

**Comment by Piasy** [comment]
I can build the latest commit of the mater branch, what's the error?

**Comment by secrecysiu** [comment]
I checkout from master branch, I can build by run ./run_djinni.sh, 

this error is in iOS_project example , seem the interface is updated

ios_project/objc/PYAAudioMixer.mm
![image](https://user-images.githubusercontent.com/50765686/57970226-6f00b380-79b1-11e9-95b9-97e123440c51.png)

**Comment by Piasy** [comment]
updated, please check it out.
