### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by zhanganl** [Piasy/AudioMixer#3]
ld: warning: directory not found for option '-L/Users/huawei/Downloads/AudioMixer-master/ios_project/../libs/webrtc/lib/iOS'
ld: warning: directory not found for option '-L/Users/huawei/Downloads/AudioMixer-master/ios_project/../libs/ffmpeg/lib/iOS'
ld: library not found for -lwebrtc
clang: error: linker command failed with exit code 1 (use -v to see invocation)

你好我编译iOS的编译通不过 请问这个缺的lwbrtc 是需要我自己编译吗？那么请问是从哪里获取编译

**Comment by Piasy** [comment]
READ THE README.
