### ISSUE TITLE
Which repository will replace Bintray?

### ISSUE THREAD

**Issue by thanhlm1991** [Piasy/AudioMixer#6]
As you known, Bintray was shut down. I can resolve implementation 'com.github.piasy:AudioMixer:1.0.2' with Maven URL "http://dl.bintray.com/piasy/maven".
Could you integrate AudioMixer into another repository?
Thank you so much

**Comment by Piasy** [comment]
Hi @thanhlm1991 , I have published version 1.0.3 to mavenCentral, please try it.
